server:
  port: 8088
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xqh_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    port: 6379
    password: 123456
    host: 127.0.0.1
    database: 0

mybatis:
  type-aliases-package: cn.gy.entity
  mapper-locations: classpath:*.xml

